src/AppBundle/Entity/Task.php
<?php

namespace AppBundle\Entity;

use AppBundle\Entity\Task\Group as TaskGroup;
use AppBundle\Entity\Model\TaggableInterface;
use AppBundle\Entity\Model\TaggableTrait;
use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Criteria;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ApiResource(
 *   attributes={
 *     "denormalization_context"={"groups"={"task"}},
 *     "normalization_context"={"groups"={"task", "delivery", "place"}}
 *   },
 *   collectionOperations={
 *     "get"={"method"="GET"},
 *     "my_tasks" = {
 *       "route_name" = "my_tasks",
 *       "swagger_context" = {
 *         "parameters" = {{
 *           "name" = "date",
 *           "in" = "path",
 *           "required" = "true",
 *           "type" = "string"
 *         }}
 *       }
 *     }
 *   },
 *   itemOperations={
 *     "get"={"method"="GET"},
 *     "task_done"={"route_name"="api_task_done"},
 *     "task_failed"={"route_name"="api_task_failed"}
 *   }
 * )
 */
class Task implements TaggableInterface
{
    use TaggableTrait;

    const TYPE_DROPOFF = 'DROPOFF';
    const TYPE_PICKUP = 'PICKUP';

    const STATUS_TODO = 'TODO';
    const STATUS_FAILED = 'FAILED';
    const STATUS_DONE = 'DONE';

    /**
     * @Groups({"task"})
     */
    private $id;

    /**
     * @Groups({"task"})
     */
    private $type = self::TYPE_DROPOFF;

    /**
     * @Groups({"task"})
     */
    private $status = self::STATUS_TODO;

    private $delivery;

    /**
     * @Groups({"task"})
     */
    private $address;

    /**
     * @Groups({"task"})
     */
    private $doneAfter;

    /**
     * @Assert\NotBlank()
     * @Groups({"task"})
     */
    private $doneBefore;

    /**
     * @Groups({"task"})
     */
    private $comments;

    /**
     * @Groups({"task"})
     */
    private $events;

    /**
     * @Groups({"task"})
     */
    private $createdAt;

    /**
     * @Groups({"task"})
     */
    private $updatedAt;

    private $previous;

    private $group;

    /**
     * @Groups({"task"})
     */
    private $assignedTo;

    public function __construct()
    {
        $this->events = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getDelivery()
    {
        return $this->delivery;
    }

    public function setDelivery($delivery)
    {
        $this->delivery = $delivery;

        return $this;
    }

    public function getType()
    {
        return $this->type;
    }

    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    public function isPickup()
    {
        return $this->type === self::TYPE_PICKUP;
    }

    public function isDropoff()
    {
        return $this->type === self::TYPE_DROPOFF;
    }

    public function getStatus()
    {
        return $this->status;
    }

    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    public function isDone()
    {
        return $this->status === self::STATUS_DONE;
    }

    public function isFailed()
    {
        return $this->status === self::STATUS_FAILED;
    }

    public function isFinished()
    {
        return $this->isDone() || $this->isFailed();
    }

    public function getAddress()
    {
        return $this->address;
    }

    public function setAddress($address)
    {
        $this->address = $address;

        return $this;
    }

    public function getDoneAfter()
    {
        return $this->doneAfter;
    }

    public function setDoneAfter(\DateTime $doneAfter = null)
    {
        $this->doneAfter = $doneAfter;

        return $this;
    }

    public function getDoneBefore()
    {
        return $this->doneBefore;
    }

    public function setDoneBefore(\DateTime $doneBefore = null)
    {
        $this->doneBefore = $doneBefore;

        return $this;
    }

    public function getComments()
    {
        return $this->comments;
    }

    public function setComments($comments)
    {
        $this->comments = $comments;

        return $this;
    }

    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    public function getEvents()
    {
        return $this->events;
    }

    public function getPrevious()
    {
        return $this->previous;
    }

    public function setPrevious(Task $previous = null)
    {
        $this->previous = $previous;

        return $this;
    }

    public function hasPrevious()
    {
        return $this->previous !== null;
    }

    public function isAssigned()
    {
        return null !== $this->assignedTo;
    }

    public function isAssignedTo(ApiUser $courier)
    {
        return $this->isAssigned() && $this->assignedTo === $courier;
    }

    public function getAssignedCourier()
    {
        return $this->assignedTo;
    }

    public function assignTo(ApiUser $courier)
    {
        $this->assignedTo = $courier;
    }

    public function unassign()
    {
        $this->assignedTo = null;
    }

    public function hasEvent($name)
    {
        foreach ($this->getEvents() as $event) {
            if ($event->getName() === $name) {
                return true;
            }
        }

        return false;
    }

    public function getLastEvent($name)
    {
        $criteria = Criteria::create()->orderBy(array("created_at" => Criteria::DESC));

        foreach ($this->getEvents()->matching($criteria) as $event) {
            if ($event->getName() === $name) {
                return $event;
            }
        }
    }

    public function getGroup()
    {
        return $this->group;
    }

    public function setGroup(TaskGroup $group = null)
    {
        $this->group = $group;

        return $this;
    }
}

src/AppBundle/Form/OrderType.php
<?php

namespace AppBundle\Form;

use AppBundle\Sylius\Order\OrderTransitions;
use SM\Factory\FactoryInterface as StateMachineFactoryInterface;
use Sylius\Component\Order\Model\OrderInterface;
use Sylius\Component\Payment\PaymentTransitions;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;

class OrderType extends AbstractType
{
    private $stateMachineFactory;
    private $authorizationChecker;

    public function __construct(
        StateMachineFactoryInterface $stateMachineFactory,
        AuthorizationCheckerInterface $authorizationChecker)
    {
        $this->stateMachineFactory = $stateMachineFactory;
        $this->authorizationChecker = $authorizationChecker;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $builder->addEventListener(
            FormEvents::POST_SET_DATA,
            function (FormEvent $event) {

                $form = $event->getForm();
                $order = $form->getData();

                $stateMachine = $this->stateMachineFactory->get($order, OrderTransitions::GRAPH);

                if ($this->authorizationChecker->isGranted('ROLE_ADMIN')) {
                    if ($stateMachine->can(OrderTransitions::TRANSITION_ACCEPT)) {
                        $form->add('accept', SubmitType::class, [
                            'label' => 'form.order.accept.label'
                        ]);
                    }
                    if ($stateMachine->can(OrderTransitions::TRANSITION_FULFILL)) {
                        $form->add('fulfill', SubmitType::class, [
                            'label' => 'form.order.fulfill.label'
                        ]);
                    }
                }

                if ($stateMachine->can(OrderTransitions::TRANSITION_CANCEL)) {
                    $form->add('cancel', SubmitType::class, [
                        'label' => 'form.order.cancel.label'
                    ]);
                }

            }
        );

        if ($this->authorizationChecker->isGranted('ROLE_ADMIN')) {
            $builder->addEventListener(
                FormEvents::POST_SET_DATA,
                function (FormEvent $event) {

                    $form = $event->getForm();
                    $order = $form->getData();

                    foreach ($order->getPayments() as $payment) {
                        $stateMachine = $this->stateMachineFactory->get($payment, PaymentTransitions::GRAPH);
                        if ($stateMachine->can(PaymentTransitions::TRANSITION_COMPLETE)) {
                            $form->add(sprintf('payment_%d_complete', $payment->getId()), SubmitType::class, [
                                'label' => 'form.order.payment_complete.label'
                            ]);
                        }
                    }
                }
            );
        }

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => OrderInterface::class,
        ));
    }
}

src/AppBundle/Controller/OrderController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Address;
use AppBundle\Entity\Delivery;
use AppBundle\Entity\Restaurant;
use AppBundle\Entity\StripePayment;
use AppBundle\Form\DeliveryAddressType;
use AppBundle\Form\StripePaymentType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sylius\Component\Payment\Model\PaymentInterface;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Route("/order")
 */
class OrderController extends Controller
{
    /**
     * @Route("/", name="order")
     * @Template()
     */
    public function indexAction(Request $request)
    {
        $order = $this->get('sylius.context.cart')->getCart();
        $user = $this->getUser();

        // At this step, we are pretty sure the customer is logged in
        // Make sure the order actually has a customer, if not set previously
        // @see AppBundle\EventListener\WebAuthenticationListener
        if ($user !== $order->getCustomer()) {
            $order->setCustomer($user);
            $this->get('sylius.manager.order')->flush();
        }

        // TODO Check if cart is empty
        $deliveryAddress = $order->getShippingAddress();

        $form = $this->createForm(DeliveryAddressType::class, $deliveryAddress);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $deliveryAddress = $form->getData();
            $deliveryAddress->setFirstName($user->getGivenName());
            $deliveryAddress->setLastName($user->getFamilyName());
            $deliveryAddress->setTelephone($user->getTelephone());
            $this->getDoctrine()->getManagerForClass(Address::class)->persist($deliveryAddress);
            $this->getDoctrine()->getManagerForClass(Address::class)->flush();

            return $this->redirectToRoute('order_payment');
        }

        return array(
            'order' => $order,
            'form' => $form->createView(),
            'restaurant' => $order->getRestaurant(),
            'deliveryAddress' => $deliveryAddress,
        );
    }

    /**
     * @Route("/payment", name="order_payment")
     * @Template()
     */
    public function paymentAction(Request $request)
    {
        $order = $this->get('sylius.context.cart')->getCart();
        $orderManager = $this->get('coopcycle.order_manager');

        $stripePayment = $order->getLastPayment(PaymentInterface::STATE_CART);

        $form = $this->createForm(StripePaymentType::class);

        $parameters =  [
            'order' => $order,
            'deliveryAddress' => $order->getShippingAddress(),
            'restaurant' => $order->getRestaurant(),
            'form' => $form->createView(),
        ];

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $stripePayment->setStripeToken($form->get('stripeToken')->getData());

            $orderManager->create($order);
            $orderManager->authorizePayment($order);

            $this->get('sylius.manager.order')->flush();

            if (PaymentInterface::STATE_FAILED === $stripePayment->getState()) {
                return array_merge($parameters, [
                    'error' => $stripePayment->getLastError()
                ]);
            }

            $sessionKeyName = $this->getParameter('sylius_cart_restaurant_session_key_name');
            $request->getSession()->remove($sessionKeyName);

            return $this->redirectToRoute('profile_order', array('id' => $order->getId()));
        }

        return $parameters;
    }
}

src/AppBundle/Resources/views/Order/breadcrumb.html.twig
{% set step = 1 %}
{% if app.request.get('_route') == 'order' or app.request.get('_route') == 'order_delivery' %}
  {% set step = 2 %}
{% endif %}
{% if app.request.get('_route') == 'order_payment' %}
  {% set step = 3 %}
{% endif %}

{% if (restaurant is not defined) and (order is defined) %}
  {% set restaurant = order.restaurant %}
{% endif %}

<ol class="breadcrumb">
  <li><a href="{{ path('restaurant', {'id': restaurant.id, 'slug': restaurant.name|slugify }) }}">{{ restaurant.name }}</a></li>
  <li {% if step == 2 %}class="active"{% endif %}>
    {% if order is defined %}<a href="{{ path('order') }}">{% endif %}
    {{ 'Delivery'|trans }}
    {% if order is defined %}</a>{% endif %}
  </li>
  <li {% if step == 3 %}class="active"{% endif %}>
    {{ 'Payment'|trans }}
  </li>
</ol>

src/AppBundle/Resources/views/Order/foodtech.html.twig
{% extends layout %}

{% block breadcrumb %}
<li><a href="{{ path(breadcrumb_path) }}">{% trans %}adminDashboard.orders.title{% endtrans %}</a></li>
<li>#{{ order.id }}</li>
{% endblock %}

{% block content %}
  {% include "AppBundle::_partials/Order/orderFollow.html.twig" %}
{% endblock %}

{% block scripts %}
<script>
  window.AppData = window.AppData || {};
  window.AppData.order = {{ order_normalized|json_encode()|raw }};
</script>
<script src="{{ asset('js/order-tracking.js') }}"></script>
{% endblock %}

src/AppBundle/Resources/views/Order/index.html.twig
{% extends "AppBundle::base.html.twig" %}

{% if form is defined %}
  {% form_theme form with ['AppBundle:Form:order.html.twig'] %}
{% endif %}

{% block body %}
<div class="container container--full-height">

  {% include 'AppBundle:Order:breadcrumb.html.twig' %}

  <div class="order-map__wrapper">
    <div class="row">
      <div class="col-md-3">
        <div class="order-map__column">
          {% include "AppBundle::_partials/Order/restaurantDetails.html.twig" %}
        </div>
      </div>
      <div class="col-xs-12 col-md-5 col-md-offset-4">
        <div class="order-map__column">
          {{ form_start(form) }}
            <h4>{% trans %}cart.widget.title{% endtrans %}</h4>
            {{ form_row(form.floor) }}
            {{ form_row(form.streetAddress) }}
            <div class="row">
              <div class="col-md-4">
                {{ form_row(form.postalCode) }}
              </div>
              <div class="col-md-8">
                {{ form_row(form.addressLocality) }}
              </div>
            </div>
            {{ form_row(form.description) }}
            <div class="text-center">
              <button class="btn btn-primary" type="submit">{% trans %}cart.widget.button{% endtrans %}</button>
            </div>
          {{ form_end(form) }}
        </div>
      </div>
    </div>
    <div id="map" class="order-map hidden-xs hidden-sm"></div>
  </div>
</div>
{%  endblock %}


{% block scripts %}
  <script type="text/javascript">
    window.AppData = window.AppData || {};
    window.AppData.restaurantCoordinates = {
      'lat': "{{ order.restaurant.address.geo.latitude }}",
      'lng': "{{ order.restaurant.address.geo.longitude }}"
    };
    window.AppData.customerCoordinates = {
      'lat': "{{ deliveryAddress.geo.latitude }}",
      'lng': "{{ deliveryAddress.geo.longitude }}"
    };
  </script>
  <script type="text/javascript" src="{{ asset('js/order.js') }}"></script>
{% endblock %}

src/AppBundle/Resources/views/Order/invoice.html.twig
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>{% trans %}adminDashboard.orders.invoice.title{% endtrans %}</title>
  </head>
  <body>

    <table style="width: 100%;">
      <tbody>
        <tr>
          <td><h1>{% trans %}adminDashboard.orders.invoice.title{% endtrans %} #{{ order.number }}</h1></td>
          <td style="text-align: right;">{{ order.createdAt|localizeddate('full', 'none') }}</td>
        </tr>
      </tbody>
    </table>

    <div>
      <div style="margin-bottom: 30px; width: 50%; float: left;">
        <table style="width: 100%;">
          <tbody>
            <tr>
              <td><strong>{{ order.restaurant.name }}</strong></td>
            </tr>
            <tr>
              <td>{{ order.restaurant.address.streetAddress }}</td>
            </tr>
            <tr>
              <td>{{ order.restaurant.address.postalCode }} {{ order.restaurant.address.addressLocality }}</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div style="margin-bottom: 30px; width: 50%; float: left; text-align: right;">
        {% set fullName = order.customer.givenName ~ ' ' ~ order.customer.familyName %}
        <table style="width: 100%;">
          <tbody>
            <tr>
              <td><strong>{{ fullName|trim is not empty ? fullName : order.customer.username }}</strong></td>
            </tr>
            <tr>
              <td>{{ order.shippingAddress.streetAddress }}</td>
            </tr>
            <tr>
              <td>{{ order.shippingAddress.postalCode }} {{ order.shippingAddress.addressLocality }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <div style="clear: both;"></div>

    <h2>{% trans %}adminDashboard.orders.order{% endtrans %}</h2>

    <table style="width: 100%;">
      <tbody>
      {% for item in order.items %}
        <tr>
            <td>{{ item.variant.product.name }} × {{ item.quantity }}
              {% for adjusment in item.adjustments %}
                {% if adjusment.type == 'menu_item_modifier' %}
                  <br><span style="color: #999;">{{ adjusment.label }} {{ adjusment.amount|price_format }}</span>
                  {% endif %}
              {% endfor %}
            </td>
            <td style="text-align: right; vertical-align: top;">{{ item.total|price_format }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>

    <hr>

    <table style="width: 100%;">
      <tbody>
        <tr>
          <td><strong>{% trans %}adminDashboard.orders.invoice.productsTotal{% endtrans %}</strong></td>
          <td style="text-align: right;">{{ order.itemsTotal|price_format }}</td>
        </tr>
        <tr>
          <td><strong>{% trans %}adminDashboard.orders.invoice.deliveryTotal{% endtrans %}</strong></td>
          <td style="text-align: right;">
            {% for adjusment in order.adjustments %}
              {% if adjusment.type == 'delivery' %}{{ adjusment.amount|price_format }}{% endif %}
            {% endfor %}
          </td>
        </tr>
        <tr>
          <td><strong>{% trans %}adminDashboard.orders.invoice.totalTax{% endtrans %}</strong></td>
          <td style="text-align: right;">{{ order.taxTotal|price_format }}</td>
        </tr>
        <tr>
          <td><strong>{% trans %}adminDashboard.orders.invoice.totalIncludingTax{% endtrans %}</strong></td>
          <td style="text-align: right;">{{ order.total|price_format }}</td>
        </tr>
      </tbody>
    </table>

  </body>
</html>

src/AppBundle/Resources/views/Order/payment.html.twig
{% extends "AppBundle::base.html.twig" %}

{% block body %}
<div class="container container--full-height">

  {% include 'AppBundle:Order:breadcrumb.html.twig' %}

  <div class="order-map__wrapper">
    <div class="row">
      <div class="col-md-3">
        <div class="order-map__column">
          {% include "AppBundle::_partials/Order/restaurantDetails.html.twig" %}
        </div>
      </div>
      <div class="col-xs-12 col-md-5 col-md-offset-4">
        <div class="order-map__column">
          {% if error is defined %}
            <div class="alert alert-danger">
              {{ error }}
            </div>
          {% endif %}
          {{ form_start(form) }}

            {{ form_widget(form.stripeToken) }}

            <h4>{% trans %}order.payment.title{% endtrans %}</h4>

            <div class="form-group">
              <label class="control-label hidden" for="card-element">
                {% trans %}order.payment.title{% endtrans %}
              </label>
              <div id="card-element">
                <!-- a Stripe Element will be inserted here. -->
              </div>
              <!-- Used to display form errors -->
              <div id="card-errors" role="alert"></div>
            </div>

            <div class="text-center">
              <button type="submit" class="btn btn-block btn-primary btn-payment">
                <i class="fa fa-spinner fa-spin"></i> {% trans with { '%total%': order.total|price_format } %}order.payment.total{% endtrans %}
              </button>
            </div>

          {{ form_end(form) }}
        </div>
      </div>
    </div>
    <div id="map" class="order-map hidden-xs hidden-sm"></div>
  </div>
</div>
{% endblock %}

{% block scripts %}
  <script type="text/javascript" src="https://js.stripe.com/v3/"></script>
  <script src="{{ asset('js/widgets.js') }}"></script>
  <script type="text/javascript">
    window.AppData = window.AppData || {};
    window.AppData.restaurantCoordinates = {
      'lat': "{{ order.restaurant.address.geo.latitude }}",
      'lng': "{{ order.restaurant.address.geo.longitude }}"
    };
    window.AppData.customerCoordinates = {
      'lat': "{{ deliveryAddress.geo.latitude }}",
      'lng': "{{ deliveryAddress.geo.longitude }}"
    };
    new CoopCycle.StripePaymentForm(document.querySelector('form[name="stripe_payment"]'), {
      publishableKey: "{{ coopcycle_setting('stripe_publishable_key') }}",
      tokenElement: document.querySelector('#stripe_payment_stripeToken')
    })
  </script>
  <script type="text/javascript" src="{{ asset('js/order.js') }}"></script>
{% endblock %}

src/AppBundle/Resources/views/Order/service.html.twig
{% extends layout %}

{% block breadcrumb %}
<li><a href="{{ path('admin_orders') }}">{% trans %}adminDashboard.orders.title{% endtrans %}</a></li>
<li>#{{ order.id }}</li>
{% endblock %}

{% block content %}

{{ form_start(form) }}

{% include '@App/_partials/Order/navbar.html.twig' %}

{% if form.accept is defined %}
  <div class="alert alert-info">
    <i class="fa fa-info-circle"></i> {{ 'form.order.accept.help'|trans }}
  </div>
{% endif %}

<div class="row">
  <div class="col-md-7">
    {% include '@App/_partials/Order/items.html.twig' %}
    <div class="form-group">
      <label class="control-label">Notes</label>
      <textarea class="form-control" disabled>{{ order.notes }}</textarea>
    </div>
    <div class="row">
      <div class="col-md-6">
        {% if form.cancel is defined %}
          {{ form_widget(form.cancel, { attr: { class: 'btn btn-block btn-danger' } }) }}
        {% else %}
          <button class="btn btn-block btn-danger" disabled>{{ 'form.order.cancel.label'|trans }}</button>
        {% endif %}
      </div>
      <div class="col-md-6">
      {% if form.accept is defined %}
        {{ form_widget(form.accept, { attr: { class: 'btn btn-block btn-success' } }) }}
      {% endif %}
      {% if form.fulfill is defined %}
        {{ form_widget(form.fulfill, { attr: { class: 'btn btn-block btn-success' } }) }}
      {% endif %}
      </div>
    </div>
  </div>
  <div class="col-md-5">

    {% if is_granted('ROLE_ADMIN') %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">Client</h4>
      </div>
      <div class="panel-body">
        <i class="fa fa-user"></i>  
        <a href="{{ path('admin_user_details', { username: order.customer.username }) }}">
          {{ order.customer.username }}
        </a>
        <br>
        <i class="fa fa-envelope"></i>  {{ order.customer.email }}
        {% if order.customer.telephone is not empty %}
        <br>
        <i class="fa fa-phone"></i>  {{ order.customer.telephone|phone_number_format('NATIONAL') }}
        {% endif %}
      </div>
    </div>
    {% endif %}

    {% if order.billingAddress is not null %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">Adresse de facturation</h4>
      </div>
      <div class="panel-body">
        {{ order.billingAddress.firstName }} {{ order.billingAddress.lastName }}
        <br>
        {% if order.billingAddress.company is not empty %}
        {{ order.billingAddress.company }}
        <br>
        {% endif %}
        {{ order.billingAddress.streetAddress }}
        <br>
        {{ order.billingAddress.postalCode }} {{ order.billingAddress.addressLocality }}
      </div>
    </div>
    {% endif %}

  </div>
</div>

<hr>

<h3 id="delivery">Livraison</h3>

<div class="row">
  <div class="col-md-7">
    <div class="map-container" style="min-height: 250px;">
      <div class="map-container__map" id="map"></div>
    </div>
  </div>
  <div class="col-md-5">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title"><i class="fa fa-cube"></i>  Retrait</h4>
      </div>
      <div class="panel-body">
        {{ delivery.pickup.address.streetAddress }}
        <br>
        {{ delivery.pickup.doneBefore|localizeddate('medium', 'short') }}
        {% if delivery.pickup.address.description is not empty %}
        <br>
        <br>
        <textarea class="form-control" disabled>
          {{ delivery.pickup.address.description }}
        </textarea>
        {% endif %}
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title"><i class="fa fa-flag"></i>  Dépôt</h4>
      </div>
      <div class="panel-body">
        {{ delivery.dropoff.address.streetAddress }}
        <br>
        {{ delivery.dropoff.doneBefore|localizeddate('medium', 'short') }}
        {% if delivery.dropoff.address.description is not empty %}
        <br>
        <br>
        <textarea class="form-control" disabled>
          {{ delivery.pickup.address.description }}
        </textarea>
        {% endif %}
      </div>
    </div>
  </div>
</div>

<hr>

<h3 id="payments">Paiements</h3>

<table class="table">
  <thead>
    <th>État</th>
    <th class="text-right">Montant</th>
    <th class="text-right">Dernière mise à jour</th>
    <th></th>
  </thead>
  <tbody>
    {% for payment in order.payments %}
    <tr>
      <td>
        {% include '@App/_partials/Payment/state.html.twig' with { payment: payment } %}
      </td>
      <td class="text-right">
        {{ payment.amount|price_format }}
      </td>
      <td class="text-right">
        {{ payment.updatedAt|localizeddate('medium', 'short') }}
      </td>
      <td class="text-right">
        {% set payment_complete_name = 'payment_' ~ payment.id ~ '_complete' %}
        {% if form[payment_complete_name] is defined %}
          {{ form_widget(form[payment_complete_name], { attr: { class: 'btn btn-xs btn-success' } }) }}
        {% endif %}
      </td>
    </tr>
    {% endfor %}
  <tbody>
</table>

{{ form_end(form) }}

{% endblock %}

{% block scripts %}
<script src="{{ asset('js/widgets.js') }}"></script>
<script>
new CoopCycle.DeliveryMap('map', {
  pickup: [ {{ delivery.pickup.address.geo.latitude }}, {{ delivery.pickup.address.geo.longitude }} ],
  dropoff: [ {{ delivery.dropoff.address.geo.latitude }}, {{ delivery.dropoff.address.geo.longitude }} ],
  polyline: "{{ delivery.polyline|e('js') }}"
})
</script>
{% endblock %}