src/AppBundle/Entity/Restaurant.php
<?php

namespace AppBundle\Entity;

use ApiPlatform\Core\Annotation\ApiProperty;
use ApiPlatform\Core\Annotation\ApiResource;
use AppBundle\Entity\Base\FoodEstablishment;
use AppBundle\Filter\RestaurantFilter;
use AppBundle\Utils\ValidationUtils;
use AppBundle\Validator\Constraints as CustomAssert;
use Doctrine\Common\Collections\Criteria;
use Doctrine\Common\Collections\ArrayCollection;
use Sylius\Component\Product\Model\ProductInterface;
use Sylius\Component\Product\Model\ProductOptionInterface;
use Sylius\Component\Taxonomy\Model\TaxonInterface;
use Symfony\Component\ExpressionLanguage\ExpressionLanguage;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use Symfony\Component\Validator\Validation;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * A restaurant.
 *
 * @see http://schema.org/Restaurant Documentation on Schema.org
 *
 * @ApiResource(iri="http://schema.org/Restaurant",
 *   attributes={
 *     "filters"={RestaurantFilter::class},
 *     "denormalization_context"={"groups"={"order_create"}},
 *     "normalization_context"={"groups"={"restaurant", "place", "order"}}
 *   },
 *   collectionOperations={
 *     "get"={"method"="GET"}
 *   },
 *   itemOperations={
 *     "get"={"method"="GET"},
 *     "restaurant_menu"={"route_name"="api_restaurant_menu"},
 *   }
 * )
 * @Vich\Uploadable
 * @CustomAssert\IsActivableRestaurant(groups="activable")
 */
class Restaurant extends FoodEstablishment
{
    /**
     *  Delay for preparation (in minutes)
     */
    const PREPARATION_DELAY = 20;

    /**
     *  Delay for delivery (in minutes)
     */
    const DELIVERY_DELAY = 25;

    /**
     *  Delay for preparation + delivery (in minutes)
     */
    const PREPARATION_AND_DELIVERY_DELAY = self::PREPARATION_DELAY + self::DELIVERY_DELAY;

    /**
     *
     * Checkout duration (in minutes)
     * We need to take into account the time the user will take to complete checkout.
     *
     */
    const CHECKOUT_MAX_DURATION = 5;

    /**
     *  We allow ordering for the next two opened days
     */
    const NUMBER_OF_AVAILABLE_DAYS = 2;

    /**
     * @var int
     *
     * @Groups({"restaurant"})
     */
    private $id;

    /**
     * @var string The name of the item
     *
     * @Assert\Type(type="string")
     * @ApiProperty(iri="http://schema.org/name")
     * @Groups({"restaurant", "order"})
     */
    protected $name;

    /**
     * @var string The cuisine of the restaurant.
     *
     * @ApiProperty(iri="https://schema.org/servesCuisine")
     * @Groups({"restaurant"})
     */
    protected $servesCuisine;

    /**
     * @var boolean Is the restaurant enabled?
     *
     * A disable restaurant is not shown to visitors, but remain accessible in preview to admins and owners.
     *
     * @Groups({"restaurant"})
     *
     */
    protected $enabled = false;

    /**
     * @var integer Additional time to delay ordering
     *
     */
    protected $orderingDelayMinutes = 0;

    /**
     * @Vich\UploadableField(mapping="restaurant_image", fileNameProperty="imageName")
     * @Assert\File(maxSize = "1024k")
     * @var File
     */
    private $imageFile;

    /**
     * @var string
     */
    private $imageName;

    /**
     * @var Address
     *
     * @Groups({"restaurant", "order"})
     */
    private $address;

    /**
     * @var string The website of the restaurant.
     *
     * @ApiProperty(iri="https://schema.org/URL")
     */
    private $website;

    /**
     * @var StripeAccount The StripeAccount of the restaurant.
     */
    private $stripeAccount;

    /**
     * @var string
     *
     * @Assert\Type(type="string")
     */
    private $deliveryPerimeterExpression = 'distance < 3000';

    private $closingRules;

    private $createdAt;

    private $updatedAt;

    private $owners;

    private $products;

    private $productOptions;

    /**
     * @Groups({"restaurant"})
     */
    private $taxons;

    private $activeMenuTaxon;

    /**
     * @var Contract
     * @Groups({"order_create"})
     */
    private $contract;

    public function __construct()
    {
        $this->servesCuisine = new ArrayCollection();
        $this->closingRules = new ArrayCollection();
        $this->owners = new ArrayCollection();
        $this->products = new ArrayCollection();
        $this->productOptions = new ArrayCollection();
        $this->taxons = new ArrayCollection();
    }

    /**
     * Gets id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Sets name.
     *
     * @param string $name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Gets name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @return bool
     */
    public function isEnabled()
    {
        return $this->enabled;
    }

    /**
     * @param bool $enabled
     */
    public function setEnabled(bool $enabled)
    {
        $this->enabled = $enabled;
    }

    public function getWebsite()
    {
        return $this->website;
    }

    public function setWebsite($website)
    {
        $this->website = $website;

        return $this;
    }

    public function setImageName($imageName)
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getImageName()
    {
        return $this->imageName;
    }

    public function getAddress()
    {
        return $this->address;
    }

    public function setAddress(Address $address)
    {
        $this->address = $address;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the  update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|Symfony\Component\HttpFoundation\File\UploadedFile $image
     */
    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        if ($image) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @return mixed
     */
    public function getClosingRules()
    {
        return $this->closingRules;
    }

    /**
     * @param mixed $closingRules
     */
    public function setClosingRules($closingRules)
    {
        $this->closingRules = $closingRules;
    }

    public function hasClosingRuleForNow(\DateTime $now = null) {
        if (!$now) {
            $now = new \DateTime();
        }

        $criteria = Criteria::create()->where(Criteria::expr()->andX(
                Criteria::expr()->lte("startDate", $now),
                Criteria::expr()->gte("endDate", $now)
            ));

        return $this->closingRules->matching($criteria)->count() > 0;

    }

    /**
     * Return potential delivery times for a restaurant, pickables by the customer.
     *
     * @param \DateTime|null $now
     * @return array
     */
    public function getAvailabilities(\DateTime $now = null) {

        if (!$now) {
            $now = new \DateTime();
        }

        $now->modify('+'.(self::CHECKOUT_MAX_DURATION + self::PREPARATION_AND_DELIVERY_DELAY + $this->getOrderingDelayMinutes()).' minutes');

        $nextOpeningDate = $this->getNextOpeningDate($now);

        if (is_null($nextOpeningDate)) {
            return [];
        }

        $date =  clone $nextOpeningDate;

        $availabilities = [$date->format(\DateTime::ATOM)];

        $currentDay = $date->format('Ymd');
        $dayCount = 1;

        while ($dayCount <= self::NUMBER_OF_AVAILABLE_DAYS) {

            $date->modify('+15 minutes');

            $nextOpeningDate = $this->getNextOpeningDate($date);

            if (is_null($nextOpeningDate)) {
                return $availabilities;
            }

            $nextOpenedDate = clone $nextOpeningDate;

            $day = $nextOpenedDate->format('Ymd');

            if ($day !== $currentDay) {
                $currentDay = $day;
                $dayCount++;
            }
            else {
                $date = $nextOpenedDate;
                if (!$this->hasClosingRuleForNow($date)) {
                    $availabilities[] = $date->format(\DateTime::ATOM);
                }
            }
        }

        return $availabilities;
    }

    public function setServesCuisine($servesCuisine)
    {
        $this->servesCuisine = $servesCuisine;

        return $this;
    }

    public function addServesCuisine($servesCuisine)
    {
        $this->servesCuisine->add($servesCuisine);

        return $this;
    }

    public function getServesCuisine()
    {
        return $this->servesCuisine;
    }

    public function getStripeAccount()
    {
        return $this->stripeAccount;
    }

    public function setStripeAccount(StripeAccount $stripeAccount)
    {
        $this->stripeAccount = $stripeAccount;

        return $this;
    }

    public function getMenuTaxon()
    {
        return $this->activeMenuTaxon;
    }

    public function setMenuTaxon(TaxonInterface $taxon)
    {
        $this->activeMenuTaxon = $taxon;
    }

    /**
     * @return string
     */
    public function getDeliveryPerimeterExpression()
    {

src/AppBundle/Form/RestaurantType.php
<?php

namespace AppBundle\Form;

use AppBundle\Entity\Restaurant;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RestaurantType extends LocalBusinessType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);

        $builder
            ->add('orderingDelayDays', IntegerType::class, [
                'label' => 'localBusiness.form.orderingDelayDays',
                'mapped' => false
            ])
            ->add('orderingDelayHours', IntegerType::class, [
                'label' => 'localBusiness.form.orderingDelayHours',
                'mapped' => false
            ]);

        if ($this->authorizationChecker->isGranted('ROLE_ADMIN')) {
            $builder->add('contract', ContractType::class);
        }


        $builder->add('deliveryPerimeterExpression', HiddenType::class, ['label' => 'localBusiness.form.deliveryPerimeterExpression',]);

        $builder->addEventListener(FormEvents::POST_SET_DATA, function (FormEvent $event) use ($options) {
            $restaurant = $event->getData();
            $form = $event->getForm();
            $orderingDelayMinutes = $restaurant->getOrderingDelayMinutes();
            $orderingDelayDays = $orderingDelayMinutes / (60 * 24);
            $remainder = $orderingDelayMinutes % (60 * 24);
            $orderingDelayHours = $remainder / 60;

            $form->get('orderingDelayHours')->setData($orderingDelayHours);
            $form->get('orderingDelayDays')->setData($orderingDelayDays);
        });

        $builder->addEventListener(
            FormEvents::POST_SUBMIT,
            function (FormEvent $event) use ($options) {
                $restaurant = $event->getForm()->getData();
                $orderingDelayDays = $event->getForm()->get('orderingDelayDays')->getData();
                $orderingDelayHours = $event->getForm()->get('orderingDelayHours')->getData();
                $restaurant->setOrderingDelayMinutes($orderingDelayDays * 60 * 24 + $orderingDelayHours * 60);
            }
        );

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver);

        $resolver->setDefaults(array(
            'data_class' => Restaurant::class,
        ));
    }
}

src/AppBundle/Resources/views/Restaurant/index.html.twig
{% extends "AppBundle::base.html.twig" %}
{% set restaurant_edit_route = is_granted('ROLE_ADMIN') ? 'admin_restaurant' : 'profile_restaurant' %}
{% set restaurant_edit_url = path(restaurant_edit_route, { id: restaurant.id }) %}

{% block body %}
<div class="container">

  {% if not restaurant.enabled %}
    <div class="row">
      <div class="col-md-6 col-md-offset-3 alert alert-danger">
        {{ "restaurant.disabledWarning" | trans({'%restaurantEditUrl%': restaurant_edit_url}) | raw }}
      </div>
    </div>
  {%  endif %}

  {% if restaurant.hasClosingRuleForNow %}
    <div class="row">
      <div class="col-md-6 col-md-offset-3 alert alert-danger">
        {% trans %}restaurant.temporaryClosedWarning{% endtrans %}
      </div>
    </div>
  {% elseif not restaurant.isOpen %}
    <div class="row">
      <div class="col-md-6 col-md-offset-3 alert alert-warning">
        {% trans %}restaurant.closedWarning{% endtrans %}
      </div>
    </div>
  {%  endif %}

  <div class="page-header restaurant-header">
    {% set restaurant_image = vich_uploader_asset(restaurant, 'imageFile') %}
    {% if restaurant_image is not empty %}
      <div class="restaurant-image" style="background-image: url({{ vich_uploader_asset(restaurant, 'imageFile') }});">
      </div>
    {% endif %}
    <div class="restaurant-title">
      <h1>{{ restaurant.name }}</h1>
      <p>{{ restaurant.address.streetAddress }}, {{ restaurant.address.postalCode }}, {{ restaurant.address.addressLocality }}</p>
      <div id="opening-hours">
      </div>
    </div>
  </div>

  {% if restaurant.menuTaxon is not null %}
  <div class="row">

    <div class="col-xs-12 col-sm-8">
      {% for child in restaurant.menuTaxon.children %}
        {% if child.products|length > 0 %}
        <h2>{{ child.name }}</h2>
        <div class="list-group">
          {% for product in child.products %}
            {% set variant = product|sylius_resolve_variant %}
            {# TODO Skip if no variant is defined #}
            {% if not product.enabled %}
              <a class="list-group-item menu-item menu-item--unavailable">
                <span class="menu-item-content">{{ product.name }}</span>
                {% if product.description is not null %}
                  <p class="menu-item-description">{{ product.description }}</p>
                {%  endif %}
                <span class="menu-item-price"><button type="button" class="btn btn-warning btn-xs">{% trans %}restaurant.unavailable{% endtrans %}</button></span>
              </a>
            {% else %}
              <a  class="list-group-item menu-item"
                  {% if product.simple %}
                  data-product-code="{{ product.code }}"
                  href="{{ path('restaurant_add_product_to_cart', { id: restaurant.id, code: product.code }) }}"
                  {% else %}
                  data-toggle="modal"
                  data-target="#{{ product.code }}-options"
                  href="#"
                  {% endif %}>
                <span class="menu-item-content">
                  {{ product.name }}
                  {% if product.description is not null %}
                    <small class="menu-item-description">{{ product.description }}</small>
                  {%  endif %}
                </span>
                <span class="menu-item-price">{{ variant.price|price_format }}</span>
              </a>
            {% endif %}
          {% endfor %}
        </div>
        {% endif %}
      {% endfor %}
    </div>

    <div class="col-xs-12 col-sm-4">
        <div id="cart"></div>
    </div>

    <div class="visible-xs">
    </div>

  </div>

  {% else %}
    <div class="alert alert-warning">
      {% trans %}restaurant.noMenuWarning{% endtrans %}
    </div>
  {% endif %}

</div>

{# Modals for modifiers #}

{% if restaurant.menuTaxon is not null %}
  {% for child in restaurant.menuTaxon.children %}
    {% for product in child.products %}
      {% if product.enabled and not product.simple %}
      <div id="{{ product.code }}-options" class="modal fade">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <h4 class="modal-title">{{ product.name }}</h4>
            </div>
            <div class="modal-body">
              <form
                action="{{ path('restaurant_add_product_to_cart', { id: restaurant.id, code: product.code }) }}"
                data-product-options>
                {% for option in product.options %}
                <h4>
                  {{ option.name }}
                  {% if option.strategy == 'option' %} - {{ option.price|price_format }}{% endif %}
                </h4>
                <div class="list-group" {% if not option.additional %}data-product-option{% endif %}>
                  {% for option_value in option.values %}
                    <div class="list-group-item modifier-item">
                      {% if option.additional %}
                        <div class="checkbox nomargin">
                          <label>
                            <input
                              name="options[{{ option.code }}][]"
                              value="{{ option_value.code }}" type="checkbox">
                            {{ option_value.value }}
                            {% if option.strategy == 'option_value' and option_value.price > 0 %}
                              +{{ option_value.price|price_format }}
                            {% endif %}
                          </label>
                        </div>
                      {% else %}
                        <div class="radio nomargin">
                          <label>
                            <input
                              name="options[{{ option.code }}]"
                              value="{{ option_value.code }}" type="radio">
                            {{ option_value.value }}
                            {% if option.strategy == 'option_value' and option_value.price > 0 %}
                              +{{ option_value.price|price_format }}
                            {% endif %}
                          </label>
                        </div>
                      {% endif %}
                    </div>
                  {% endfor %}
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-block btn-primary" disabled>{{ 'basics.add'|trans }}</button>
              </form>
            </div>
          </div>
        </div>
      </div>
      {% endif %}
    {% endfor %}
  {% endfor %}
{% endif %}

<div id="cart-warning-modal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">{{ 'cart.modal.title'|trans }}</h4>
      </div>
      <div class="modal-body">
        <p>{{ 'cart.modal.content'|trans }}</p>
      </div>
      <div class="modal-footer">
        <button id="cart-warning-cancel" type="button" class="btn btn-default">
          {{ 'cart.modal.cancel'|trans }}
        </button>
        <button id="cart-warning-confirm" type="button" class="btn btn-primary">
          {{ 'cart.modal.confirm'|trans }}
        </button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block scripts %}
<script src="{{ asset('js/widgets.js') }}"></script>
<script>

new CoopCycle.OpeningHoursParser(document.querySelector('#opening-hours'), {
  openingHours: {{ restaurant.openingHours|json_encode()|raw }},
  locale: $('html').attr('lang')
})

$('[data-product-code]').on('click', function(e) {
  e.preventDefault();
  var $target = $(e.currentTarget);
  window.AppData.CartHelper.addProduct($target.attr('href'), 1);
})

// Make sure all (non-additional) options have been checked
$('form[data-product-options] input[type="radio"]').on('click', function(e) {

  var $options = $(this).closest('form').find('[data-product-option]');
  var checkedOptionsCount = 0;
  $options.each(function(index, el) {
    checkedOptionsCount += $(el).find('input[type="radio"]:checked').length;
  });

  if ($options.length === checkedOptionsCount) {
    $(this).closest('form').find('button[type="submit"]').attr('disabled', false);
  }
})

$('form[data-product-options]').on('submit', function(e) {
  e.preventDefault();
  var data = $(this).serializeArray();
  if (data.length > 0) {
    window.AppData.CartHelper.addProductWithOptions($(this).attr('action'), data, 1);
    $(this).closest('.modal').modal('hide');
    // Uncheck all options
    $(this).closest('form').find('input[type="radio"]:checked').prop('checked', false);
    $(this).closest('form').find('input[type="checkbox"]:checked').prop('checked', false);
  }
})

$('.modal').on('shown.bs.modal', function(e) {
  var $form = $(this).find('form[data-product-options]');
  if ($form.length === 1) {
    var $options = $form.find('[data-product-option]');
    var disabled = $options.length > 0;
    $form.find('button[type="submit"]').attr('disabled', disabled);
  }
});

function initMap() {

  $('#cart-warning-cancel').on('click', function(e) {
    {% set cart = cart_provider.getCart() %}
    window.location.replace("{{ path('restaurant', { id: cart.restaurant.id }) }}")
    $('#cart-warning-modal').modal('hide');
  })

  $('#cart-warning-confirm').on('click', function(e) {
    window.AppData.CartHelper.reset();
    $('#cart-warning-modal').modal('hide');
  })

  window.AppData.CartHelper.init(document.querySelector('#cart'), {
    restaurant: {
      id: {{ restaurant.id }},
      availabilities: {{ availabilities|json_encode()|raw }}
    },
    cartURL: "{{ path('restaurant_cart', { id: restaurant.id }) }}",
    removeFromCartURL: "{{ path('restaurant_remove_from_cart', { id: restaurant.id, cartItemId: '__CART_ITEM_ID__' }) }}",
    resetCartURL: "{{ path('restaurant_cart_reset', { id: restaurant.id }) }}",
    onCartWarning: function() {
      $('#cart-warning-modal').modal('show');
    }
  });
}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key={{ coopcycle_setting('google_api_key') }}&libraries=places&callback=initMap"></script>
{% endblock %}

src/AppBundle/Resources/views/Restaurant/layout.html.twig
{% extends layout %}

{% block subnav %}
  <nav class="navbar">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#restaurant-navbar" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <span class="navbar-brand">
          {% if restaurant.id is not empty %}
            <a href="{{ path(restaurant_route, { id: restaurant.id }) }}">{{ restaurant.name }}</a>
            &nbsp;&nbsp;
            <a href="{{ path('restaurant', { id: restaurant.id }) }}" target="_blank">
              <i class="fa fa-external-link"></i>
            </a>
          {% else %}
            {% trans %}restaurant.form.createRestaurant{% endtrans %}
          {% endif %}
        </span>
      </div>
      <div class="collapse navbar-collapse" id="restaurant-navbar">
        <div class="nav navbar-nav navbar-right">
          {% if restaurant.id is not empty %}
            <a href="{{ path(products_route, { id: restaurant.id }) }}" class="btn btn-default navbar-btn">
              <i class="fa fa-database"></i>  {% trans %}restaurant.list.products{% endtrans %}
            </a>
            <a href="{{ path(product_options_route, { id: restaurant.id }) }}" class="btn btn-default navbar-btn">
              <i class="fa fa-sliders"></i>  {% trans %}restaurant.list.product_options{% endtrans %}
            </a>

            {% if restaurant.menuTaxon is not null %}
            <a href="{{ path(menu_taxon_route, { restaurantId: restaurant.id, menuId: restaurant.menuTaxon.id }) }}"
              class="btn btn-default navbar-btn">
              <i class="fa fa-cutlery"></i>  {% trans %}restaurant.list.activeMenu{% endtrans %}
            </a>
            {% endif %}
            <a href="{{ path(menu_taxons_route, { id: restaurant.id }) }}"
              class="btn btn-default navbar-btn">
              <i class="fa fa-list"></i>  {% trans %}restaurant.list.menus{% endtrans %}
            </a>

            <a href="{{ path(dashboard_route, { restaurantId: restaurant.id }) }}" class="btn btn-default navbar-btn">
              <i class="fa fa-cube"></i>  {% trans %}restaurant.list.orders{% endtrans %}
            </a>
            <a href="{{ path(planning_route, { id: restaurant.id }) }}" class="btn btn-default navbar-btn">
              <i class="fa fa-clock-o"></i>  {% trans %}restaurant.list.planning{% endtrans %}
            </a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>
{% endblock %}

src/AppBundle/Resources/views/Restaurant/menuTaxons.html.twig
{% extends '@App/Restaurant/layout.html.twig' %}

{% block breadcrumb %}
  <li><a href="{{ path(restaurants_route) }}">{% trans %}adminDashboard.restaurants.title{% endtrans %}</a></li>
  <li><a href="{{ path(restaurant_route, { id: restaurant.id }) }}">{{ restaurant.name }}</a></li>
  <li>{% trans %}Menus{% endtrans %}</li>
{% endblock %}

{% block content %}
  {% for message in app.flashes('notice') %}
    <div class="alert alert-success">
      {{ message|raw }}
    </div>
  {% endfor %}
  <p class="text-right">
    <a class="btn btn-success" href="{{ path(new_menu_route, { id: restaurant.id }) }}">
      <i class="fa fa-plus"></i> {{ 'basics.add'|trans }}
    </a>
  </p>
  {% if menus|length > 0 %}
  <table class="table">
    <thead>
      <th></th>
      <th>Name</th>
      <th></th>
      <th></th>
    </thead>
    <tbody>
      {% for menu in menus %}
      <tr {% if restaurant.menuTaxon == menu %}class="active"{% endif %}>
        <td width="5%">
          {% if restaurant.menuTaxon == menu %}
            <i class="fa fa-check"></i>
          {% endif %}
        </td>
        <td>
          {{ menu.name }}
        </td>
        <td class="text-right" width="10%">
          {% if restaurant.menuTaxon != menu %}
            <form method="post" action="{{ path(menu_activate_route, { restaurantId: restaurant.id, menuId: menu.id }) }}">
              <button type="submit" class="btn btn-xs btn-success">
                <i class="fa fa-check"></i> {{ 'restaurant.menus.activate'|trans }}
              </button>
            </form>
          {% endif %}
        </td>
        <td class="text-right" width="10%">
          <a class="btn btn-xs btn-default" href="{{ path(menu_route, { restaurantId: restaurant.id, menuId: menu.id }) }}">
            <i class="fa fa-pencil"></i> {{ 'basics.edit'|trans }}
          </a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
    <div class="alert alert-warning">{% trans %}restaurant.menus.noMenus{% endtrans %}</div>
  {% endif %}

{% endblock %}

src/AppBundle/Resources/views/Restaurant/pagination.html.twig
<nav aria-label="...">
  <ul class="pager">
    {% set prev_page = (page > 1) ? page - 1 : 1 %}
    <li class="previous" {% if page == 1 %}style="display: none;"{% endif %}><a href="{{ path('restaurants', {'geohash': geohash, 'page': prev_page, 'datetime': searchDate}) }}"><span aria-hidden="true">&larr;</span> {%  trans  %}pagination.previous{% endtrans %}</a></li>
    {% set next_page = (page < pages) ? page + 1 : page %}
    <li class="next" {% if next_page == page %}style="display: none;"{% endif %}><a href="{{ path('restaurants', {'geohash': geohash, 'page': next_page, 'datetime': searchDate}) }}">{% trans %}pagination.next{% endtrans %} <span aria-hidden="true">&rarr;</span></a></li>
  </ul>
</nav>